// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/guirialli/go-pos/clean_arch/internals/entity"
	"github.com/guirialli/go-pos/clean_arch/internals/event"
	"github.com/guirialli/go-pos/clean_arch/internals/infra/database"
	"github.com/guirialli/go-pos/clean_arch/internals/infra/web"
	"github.com/guirialli/go-pos/clean_arch/internals/usecase"
	"github.com/guirialli/go-pos/clean_arch/pkg/events"
)

import (
	_ "github.com/go-sql-driver/mysql"
)

// Injectors from wire.go:

func NewCreateOrderUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.CreateOrderUseCase {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	createOrderUseCase := usecase.NewCreateOrderUseCase(orderRepository, orderCreated, eventDispatcher)
	return createOrderUseCase
}

func NewWebOrderHandler(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *web.OrderHandler {
	orderRepository := database.NewOrderRepository(db)
	orderCreated := event.NewOrderCreated()
	orderHandler := web.NewOrderHandler(eventDispatcher, orderRepository, orderCreated)
	return orderHandler
}

func NewFindAllOrdersUseCase(db *sql.DB, eventDispatcher events.EventDispatcherInterface) *usecase.FindAllOrdersUseCase {
	orderRepository := database.NewOrderRepository(db)
	findAllOrdersUseCase := usecase.NewFindAllOrdersUseCase(orderRepository)
	return findAllOrdersUseCase
}

// wire.go:

var setOrderRepositoryDependency = wire.NewSet(database.NewOrderRepository, wire.Bind(new(entity.OrderRepositoryInterface), new(*database.OrderRepository)))

var setEventDispatcherDependency = wire.NewSet(events.NewEventDispatcher, event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)), wire.Bind(new(events.EventDispatcherInterface), new(*events.EventDispatcher)))

var setOrderCreatedEvent = wire.NewSet(event.NewOrderCreated, wire.Bind(new(events.EventInterface), new(*event.OrderCreated)))
